PART V. Derivatices Analytics

Chapter 17. Valuation Framework

In [2]:
import numpy as np
import pandas as pd
import datetime as dt

In [3]:
from pylab import mpl, plt
plt.style.use('seaborn-v0_8')
mpl.rcParams['font.family'] = 'serif'
%config InlineBackend.figure_format = 'svg'

In [4]:
import sys
sys.path.append('../dx')

In [5]:
dates = [dt.datetime(2020, 1, 1), dt.datetime(2020, 7, 1),
         dt.datetime(2021, 1, 1)]

In [6]:
(dates[1] - dates[0]).days / 365.

0.4986301369863014

In [7]:
(dates[2] - dates[1]).days / 365.

0.5041095890410959

In [8]:
fractions = [0.0, 0.5, 1.0]

In [9]:
from get_year_deltas import get_year_deltas

In [10]:
get_year_deltas(dates)

array([0.        , 0.49863014, 1.00273973])

In [11]:
from constant_short_rate import constant_short_rate

In [12]:
csr = constant_short_rate('csr', 0.05)

In [13]:
csr.get_discount_factors(dates)

array([[datetime.datetime(2020, 1, 1, 0, 0), 1.0],
       [datetime.datetime(2020, 7, 1, 0, 0), 0.9753767163648953],
       [datetime.datetime(2021, 1, 1, 0, 0), 0.9510991280247174]],
      dtype=object)

In [15]:
deltas = get_year_deltas(dates)
deltas

array([0.        , 0.49863014, 1.00273973])

In [16]:
csr.get_discount_factors(deltas, dtobjects=False)

array([[0.        , 1.        ],
       [0.49863014, 0.97537672],
       [1.00273973, 0.95109913]])

In [17]:
from market_environment import market_environment

In [18]:
me = market_environment('me_gbm', dt.datetime(2020,1,1))

In [19]:
me.add_constant('initial_value' , 36.)

In [20]:
me.add_constant('volatility', 0.2)

In [21]:
me.add_constant('final_date', dt.datetime(2020, 12, 31))

In [22]:
me.add_constant('currency', 'EUR')

In [23]:
me.add_constant('frequency', 'M')

In [24]:

me.add_constant('paths', 10000)

In [25]:
me.add_curve('discount_curve', csr)

In [26]:
me.get_constant('volatility')

0.2

In [27]:
me.get_curve('discount_curve').short_rate

0.05