## Chapter9P Input/Output operations

In [14]:
from pylab import plt, mpl
plt.style.use('seaborn-v0_8')
mpl.rcParams['font.family'] = 'serif'
%matplotlib inline

In [15]:
import pickle
import numpy as np
from random import gauss


In [16]:
a = [gauss(1.5, 2) for i in range(1000000)]

In [17]:
path = '/Users/youngsoom4pro/Documents/GitHub/Python_Finance/Chap9/data/'

In [18]:
pkl_file = open(path+ 'data.pkl', 'wb')

In [19]:
%time pickle.dump(a, pkl_file)

CPU times: user 8.89 ms, sys: 3.22 ms, total: 12.1 ms
Wall time: 16.7 ms


In [20]:
pkl_file.close()

In [21]:
ll $path*

-rw-r--r--  1 youngsoom4pro  staff  9003247 Jan 12 10:03 /Users/youngsoom4pro/Documents/GitHub/Python_Finance/Chap9/data/data.pkl


In [22]:
pkl_file = open(path + 'data.pkl', 'rb')
# open the file for reading in binary mode(rb)

In [23]:
%time b = pickle.load(pkl_file)
# read the object from disk and deserializes it.

CPU times: user 14.7 ms, sys: 5.25 ms, total: 20 ms
Wall time: 19.4 ms


In [24]:
a[:3]

[1.1320698249652266, 1.476630923595049, 0.012594974148210092]

In [25]:
b[:3]

[1.1320698249652266, 1.476630923595049, 0.012594974148210092]

In [26]:
np.allclose(np.array(a), np.array(b))
# converting a and b to ndarray objects, np.allclose() verifies that both contain the same data (numbers)

True

In [27]:
pkl_file = open(path + 'data.pkl', 'wb')

In [28]:
%time pickle.dump(np.array(a), pkl_file)

CPU times: user 20.6 ms, sys: 1.52 ms, total: 22.1 ms
Wall time: 21.6 ms


In [29]:
%time pickle.dump(np.array(a)**2, pkl_file)

CPU times: user 20.8 ms, sys: 1.56 ms, total: 22.4 ms
Wall time: 21.8 ms


In [30]:
pkl_file.close()

In [31]:
ll $path*

-rw-r--r--  1 youngsoom4pro  staff  16000326 Jan 12 10:04 /Users/youngsoom4pro/Documents/GitHub/Python_Finance/Chap9/data/data.pkl


In [38]:
pkl_file = open(path+'data.pkl', 'rb')

In [39]:
x= pickle.load(pkl_file)
x[:4]

array([1.13206982, 1.47663092, 0.01259497, 0.01729362])

In [40]:
y= pickle.load(pkl_file)
y[:4]

array([1.28158209e+00, 2.18043888e+00, 1.58633374e-04, 2.99069432e-04])

In [41]:
pkl_file.close()

In [ ]:
pkl_file = open(path + 'data.pkl', 'wb')
pickle.dump({'x': x, 'y': y}, pkl_file) # stor a dict object containing the two ndarray objects. 
pkl_file.close()

In [ ]:
pkl_file = open(path + 'data.pkl', 'rb')
data = pickle.load(pkl_file) # retrivevs the dict object
pkl_file.close()
for key in data.keys():
    print(key, data[key][:4])

x [1.13206982 1.47663092 0.01259497 0.01729362]
y [1.28158209e+00 2.18043888e+00 1.58633374e-04 2.99069432e-04]


In [44]:
!rm -f $path*

In [65]:
import pandas as pd

In [66]:
rows = 5000
a = np.random.standard_normal((rows,5)).round(4)

In [67]:
a

array([[ 0.0239, -0.1432, -1.5996, -0.3485, -0.3744],
       [-0.0049,  0.5232,  0.9446,  1.5553,  1.3861],
       [ 2.0011, -1.7574,  0.4643,  0.6506, -0.5088],
       ...,
       [ 0.8224,  1.3386,  0.4848,  2.3684, -0.391 ],
       [-0.1792,  0.8905,  0.8534,  0.151 , -0.611 ],
       [-0.8463, -0.2085, -0.2247,  1.5383, -0.0353]], shape=(5000, 5))

In [68]:
t = pd.date_range(start='2019/1/1', periods=rows, freq='h')

In [69]:
t

DatetimeIndex(['2019-01-01 00:00:00', '2019-01-01 01:00:00',
               '2019-01-01 02:00:00', '2019-01-01 03:00:00',
               '2019-01-01 04:00:00', '2019-01-01 05:00:00',
               '2019-01-01 06:00:00', '2019-01-01 07:00:00',
               '2019-01-01 08:00:00', '2019-01-01 09:00:00',
               ...
               '2019-07-27 22:00:00', '2019-07-27 23:00:00',
               '2019-07-28 00:00:00', '2019-07-28 01:00:00',
               '2019-07-28 02:00:00', '2019-07-28 03:00:00',
               '2019-07-28 04:00:00', '2019-07-28 05:00:00',
               '2019-07-28 06:00:00', '2019-07-28 07:00:00'],
              dtype='datetime64[ns]', length=5000, freq='h')

In [70]:
csv_file = open(path+'data.csv','w')

In [71]:
header = 'date,no1,no2,no3,no4,no5\n'
# opens a file for writing (w)

In [72]:
csv_file.write(header)
# define the header row (column labels) and writes it as the first line.

25

In [73]:
for t_, (no1, no2, no3, no4, no5) in zip(t,a):
    s = '{},{},{},{},{},{}\n'.format(t_, no1, no2, no3, no4, no5)
    csv_file.write(s)

In [59]:
ll $path*

-rw-r--r--  1 youngsoom4pro  staff  246590 Jan 12 10:19 /Users/youngsoom4pro/Documents/GitHub/Python_Finance/Chap9/data/data.csv


In [74]:
csv_file = open (path+'data.csv', 'r')

In [75]:
for i in range(5):
    print(csv_file.readline(), end='')

date,no1,no2,no3,no4,no5
2019-01-01 00:00:00,0.0239,-0.1432,-1.5996,-0.3485,-0.3744
2019-01-01 01:00:00,-0.0049,0.5232,0.9446,1.5553,1.3861
2019-01-01 02:00:00,2.0011,-1.7574,0.4643,0.6506,-0.5088
2019-01-01 03:00:00,-1.2041,0.5834,1.0502,0.87,0.0731


In [76]:
csv_file.close()

In [77]:
csv_file = open(path + 'data.csv', 'r')

In [78]:
content = csv_file.readlines()

In [79]:
content[:5]

['date,no1,no2,no3,no4,no5\n',
 '2019-01-01 00:00:00,0.0239,-0.1432,-1.5996,-0.3485,-0.3744\n',
 '2019-01-01 01:00:00,-0.0049,0.5232,0.9446,1.5553,1.3861\n',
 '2019-01-01 02:00:00,2.0011,-1.7574,0.4643,0.6506,-0.5088\n',
 '2019-01-01 03:00:00,-1.2041,0.5834,1.0502,0.87,0.0731\n']

In [80]:
csv_file.close()

In [84]:
import csv
csv.field_size_limit(100000000)

131072

In [85]:
with open(path + 'data.csv', 'r') as f:
    csv_reader = csv.reader(f)
    lines = [line for line in csv_reader]

In [86]:
lines[:5]

[['date', 'no1', 'no2', 'no3', 'no4', 'no5'],
 ['2019-01-01 00:00:00', '0.0239', '-0.1432', '-1.5996', '-0.3485', '-0.3744'],
 ['2019-01-01 01:00:00', '-0.0049', '0.5232', '0.9446', '1.5553', '1.3861'],
 ['2019-01-01 02:00:00', '2.0011', '-1.7574', '0.4643', '0.6506', '-0.5088'],
 ['2019-01-01 03:00:00', '-1.2041', '0.5834', '1.0502', '0.87', '0.0731']]

In [87]:
with open(path+'data.csv','r') as f:
    csv_reader = csv.DictReader(f)
    lines = [line for line in csv_reader]

In [88]:
lines[:3]

[{'date': '2019-01-01 00:00:00',
  'no1': '0.0239',
  'no2': '-0.1432',
  'no3': '-1.5996',
  'no4': '-0.3485',
  'no5': '-0.3744'},
 {'date': '2019-01-01 01:00:00',
  'no1': '-0.0049',
  'no2': '0.5232',
  'no3': '0.9446',
  'no4': '1.5553',
  'no5': '1.3861'},
 {'date': '2019-01-01 02:00:00',
  'no1': '2.0011',
  'no2': '-1.7574',
  'no3': '0.4643',
  'no4': '0.6506',
  'no5': '-0.5088'}]

In [89]:
!rm -f $path*

In [90]:
import sqlite3 as sq3

In [ ]:
con = sq3.connect(path+'numbs.db')
# open database connection; a file is created if it does not exist

In [ ]:
query = 'CREATE TABLE numbs (Date date, No1 real, No2 real)'
# A SQL query that creates a table with three columns

In [ ]:
con.execute(query)
# executes the query


In [ ]:
con.commit()
# and commits the changes

In [ ]:
q = con.execute
# defines a short alias for the con.execute() method

In [ ]:
q('SELECT * FROM sqlite_master').fetchall()
# fetches metainformation about the database, showing the just-created table as the single object.

[('table',
  'numbs',
  'numbs',
  2,
  'CREATE TABLE numbs (Date date, No1 real, No2 real)')]

In [97]:
import datetime

In [98]:
now = datetime.datetime.now()
q('INSERT INTO numbs VALUES(?,?,?)', (now, 0.12, 7.3))

/var/folders/ff/0rjbdk056r39pjbd0rm8g6440000gn/T/ipykernel_18455/3105697824.py:2: DeprecationWarning: The default datetime adapter is deprecated as of Python 3.12; see the sqlite3 documentation for suggested replacement recipes
  q('INSERT INTO numbs VALUES(?,?,?)', (now, 0.12, 7.3))


In [ ]:
# writes a single row (or record) to the numbs table.
np.random.seed(100)

In [ ]:
# create a larger dummy data set as an ndarray object
data = np.random.standard_normal((10000,2)).round(4)

In [ ]:
%%time
# iterate over the rows of the ndarray object.
for row in data:
    now = datetime.datetime.now()
    q('INSERT INTO numbs VALUES(?,?,?)', (now, row[0], row[1]))
con.commit()
    

CPU times: user 27.2 ms, sys: 3.55 ms, total: 30.8 ms
Wall time: 29.5 ms


<timed exec>:3: DeprecationWarning: The default datetime adapter is deprecated as of Python 3.12; see the sqlite3 documentation for suggested replacement recipes


In [ ]:
# Retrieves a number of rows from the table
q('SELECT * FROM numbs').fetchmany(4)

[('2026-01-12 10:40:10.512673', 0.12, 7.3),
 ('2026-01-12 10:43:06.348036', -1.7498, 0.3427),
 ('2026-01-12 10:43:06.348299', 1.153, -0.2524),
 ('2026-01-12 10:43:06.348326', 0.9813, 0.5142)]

In [107]:
q('SELECT * FROM numbs WHERE no1>0.5').fetchmany(4)

[('2026-01-12 10:43:06.348299', 1.153, -0.2524),
 ('2026-01-12 10:43:06.348326', 0.9813, 0.5142),
 ('2026-01-12 10:43:06.348567', 0.6727, -0.1044),
 ('2026-01-12 10:43:06.348613', 1.619, 1.5416)]

In [ ]:
# define pointer object
pointer = q('SELECT * FROM numbs')

In [ ]:
# ... that behaves like a generator object
for i in range(3):
    print(pointer.fetchone())

('2026-01-12 10:40:10.512673', 0.12, 7.3)
('2026-01-12 10:43:06.348036', -1.7498, 0.3427)
('2026-01-12 10:43:06.348299', 1.153, -0.2524)


In [ ]:
# retrives all the remaining rows.
rows = pointer.fetchall()
rows[:3]

[('2026-01-12 10:43:06.348326', 0.9813, 0.5142),
 ('2026-01-12 10:43:06.348423', 0.2212, -1.07),
 ('2026-01-12 10:43:06.348473', -0.1895, 0.255)]

In [ ]:
q('DROP TABLE IF EXISTS numbs')
#removes the table from database.

In [118]:
q('SELECT * FROM sqlite_master').fetchall()

[]

In [119]:
con.close()