Chap 4. Numerical Computing with Numpy

In [2]:
v = [0.5, 0.75 , 1.0, 1.5, 2.0]

In [4]:
m = [v,v,v]
m

[[0.5, 0.75, 1.0, 1.5, 2.0],
 [0.5, 0.75, 1.0, 1.5, 2.0],
 [0.5, 0.75, 1.0, 1.5, 2.0]]

In [5]:
m[1]

[0.5, 0.75, 1.0, 1.5, 2.0]

In [6]:
m[1][0]

0.5

In [7]:
v1 = [0.2, 1.5]
v2 = [1, 2]
m=[v1, v2]
c= [m, m]
c

[[[0.2, 1.5], [1, 2]], [[0.2, 1.5], [1, 2]]]

In [8]:
c[1][1][0]

1

In [9]:
v = [0.5, 0.75 , 1.0, 1.5, 2.0]
m = [v, v, v]
m

[[0.5, 0.75, 1.0, 1.5, 2.0],
 [0.5, 0.75, 1.0, 1.5, 2.0],
 [0.5, 0.75, 1.0, 1.5, 2.0]]

In [10]:
v[0] = 'Python'
m

[['Python', 0.75, 1.0, 1.5, 2.0],
 ['Python', 0.75, 1.0, 1.5, 2.0],
 ['Python', 0.75, 1.0, 1.5, 2.0]]

In [11]:
from copy import deepcopy
v = [0.5, 0.75 , 1.0, 1.5, 2.0]
m = 3*[deepcopy(v),]
m

[[0.5, 0.75, 1.0, 1.5, 2.0],
 [0.5, 0.75, 1.0, 1.5, 2.0],
 [0.5, 0.75, 1.0, 1.5, 2.0]]

In [12]:
v[0] = 'Pytho'
m

[[0.5, 0.75, 1.0, 1.5, 2.0],
 [0.5, 0.75, 1.0, 1.5, 2.0],
 [0.5, 0.75, 1.0, 1.5, 2.0]]

In [13]:
v

['Pytho', 0.75, 1.0, 1.5, 2.0]

In [14]:
v = [0.5, 0.75 , 1.0, 1.5, 2.0]


In [15]:
import array

In [16]:
a = array.array('f', v)
a

array('f', [0.5, 0.75, 1.0, 1.5, 2.0])

In [17]:
a.append(0.5)
a

array('f', [0.5, 0.75, 1.0, 1.5, 2.0, 0.5])

In [18]:
a.extend([5.0, 6.75])

In [19]:
a

array('f', [0.5, 0.75, 1.0, 1.5, 2.0, 0.5, 5.0, 6.75])

In [20]:
a*2

array('f', [0.5, 0.75, 1.0, 1.5, 2.0, 0.5, 5.0, 6.75, 0.5, 0.75, 1.0, 1.5, 2.0, 0.5, 5.0, 6.75])

In [21]:
a.append('string')

TypeError: must be real number, not str

In [22]:
a.tolist()

[0.5, 0.75, 1.0, 1.5, 2.0, 0.5, 5.0, 6.75]

In [24]:
f = open('array.apy', 'wb')
a.tofile(f)
f.close()

In [25]:
with open('array.apy','wb') as f:
    a.tofile(f)

In [26]:
!ls -n arr*

-rw-rw-r-- 1 1000 1000 32 Jan  3 14:10 array.apy


In [27]:
b = array.array('f')

In [29]:
with open('array.apy', 'rb') as f:
    b.fromfile(f, 5)

In [30]:
b

array('f', [0.5, 0.75, 1.0, 1.5, 2.0])

In [33]:
b = array.array('d')
# the dfference in type codes lead to "wrong" numbers
with  open ('array.apy', 'rb') as f:
    b.fromfile(f, 2)

In [32]:
b

array('d', [0.0004882813645963324, 0.12500002956949174])

In [1]:
import numpy as np

In [2]:
a = np.array([0, 0.5, 1.0 ,1.5, 2.0])
a

array([0. , 0.5, 1. , 1.5, 2. ])

In [3]:
type(a)

numpy.ndarray

In [4]:
a = np.array(['a', 'b', 'c'])
a

array(['a', 'b', 'c'], dtype='<U1')

In [6]:
a = np.arange(2,20,2)
a

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [9]:
a = np.arange(8, dtype=np.float64)
a

array([0., 1., 2., 3., 4., 5., 6., 7.])

In [10]:
a[5:]

array([5., 6., 7.])

In [11]:
a[:2]

array([0., 1.])

In [12]:
a.sum()

np.float64(28.0)

In [13]:
a.std()

np.float64(2.29128784747792)

In [ ]:
a.cumsum()
# the cumulative sum of all elements (starting at index position 0)

array([ 0.,  1.,  3.,  6., 10., 15., 21., 28.])

In [ ]:
l = [0., 0.5, 1.5, 3., 5.]
2*l
# scalar multiplication with list objects leads to a repetition of elements

[0.0, 0.5, 1.5, 3.0, 5.0, 0.0, 0.5, 1.5, 3.0, 5.0]

In [16]:
a

array([0., 1., 2., 3., 4., 5., 6., 7.])

In [17]:
2*a

array([ 0.,  2.,  4.,  6.,  8., 10., 12., 14.])

In [18]:
2**a

array([  1.,   2.,   4.,   8.,  16.,  32.,  64., 128.])

In [19]:
a**2

array([ 0.,  1.,  4.,  9., 16., 25., 36., 49.])

In [20]:
a**a

array([1.00000e+00, 1.00000e+00, 4.00000e+00, 2.70000e+01, 2.56000e+02,
       3.12500e+03, 4.66560e+04, 8.23543e+05])

In [21]:
type(a)

numpy.ndarray

In [22]:
type(l)

list

In [23]:
np.exp(a)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03])

In [24]:
np.sqrt(a)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131])

In [25]:
np.sqrt(2.5)

np.float64(1.5811388300841898)

In [28]:
import math
math.sqrt(2.5)

1.5811388300841898

In [29]:
math.sqrt(a)

TypeError: only 0-dimensional arrays can be converted to Python scalars

In [30]:
%timeit np.sqrt(2.5)

45 ns ± 0.148 ns per loop (mean ± std. dev. of 7 runs, 10,000,000 loops each)


In [31]:
%timeit math.sqrt(2.5)

13 ns ± 0.144 ns per loop (mean ± std. dev. of 7 runs, 100,000,000 loops each)


In [32]:
b = np.array([a, a*2])
b

array([[ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.],
       [ 0.,  2.,  4.,  6.,  8., 10., 12., 14.]])

In [33]:
b[0]

array([0., 1., 2., 3., 4., 5., 6., 7.])

In [34]:
b[0,2]

np.float64(2.0)

In [35]:
b[:,1]

array([1., 2.])

In [36]:
b.sum()

np.float64(84.0)

In [37]:
b.sum(axis=0)

array([ 0.,  3.,  6.,  9., 12., 15., 18., 21.])

In [38]:
b.sum(axis=1)

array([28., 56.])

In [40]:
c = np.zeros((2,3), dtype='i', order='C')
c

array([[0, 0, 0],
       [0, 0, 0]], dtype=int32)

In [41]:
c = np.ones((2,3,4), dtype='i', order='C')
c

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int32)

In [52]:
d = np.zeros_like(c, dtype='f8', order='C')
d

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [45]:
e = np.empty((2,3,2))
e

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

In [54]:
f= np.empty_like(c)
f

array([[[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]]], dtype=int32)

In [55]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [62]:
g = np.linspace(5,15,12)

In [63]:
g

array([ 5.        ,  5.90909091,  6.81818182,  7.72727273,  8.63636364,
        9.54545455, 10.45454545, 11.36363636, 12.27272727, 13.18181818,
       14.09090909, 15.        ])