Chap 4. Numerical Computing with Numpy

In [40]:
v = [0.5, 0.75 , 1.0, 1.5, 2.0]

In [41]:
m = [v,v,v]
m

[[0.5, 0.75, 1.0, 1.5, 2.0],
 [0.5, 0.75, 1.0, 1.5, 2.0],
 [0.5, 0.75, 1.0, 1.5, 2.0]]

In [42]:
m[1]

[0.5, 0.75, 1.0, 1.5, 2.0]

In [43]:
m[1][0]

0.5

In [44]:
v1 = [0.2, 1.5]
v2 = [1, 2]
m=[v1, v2]
c= [m, m]
c

[[[0.2, 1.5], [1, 2]], [[0.2, 1.5], [1, 2]]]

In [45]:
c[1][1][0]

1

In [46]:
v = [0.5, 0.75 , 1.0, 1.5, 2.0]
m = [v, v, v]
m

[[0.5, 0.75, 1.0, 1.5, 2.0],
 [0.5, 0.75, 1.0, 1.5, 2.0],
 [0.5, 0.75, 1.0, 1.5, 2.0]]

In [47]:
v[0] = 'Python'
m

[['Python', 0.75, 1.0, 1.5, 2.0],
 ['Python', 0.75, 1.0, 1.5, 2.0],
 ['Python', 0.75, 1.0, 1.5, 2.0]]

In [48]:
from copy import deepcopy
v = [0.5, 0.75 , 1.0, 1.5, 2.0]
m = 3*[deepcopy(v),]
m

[[0.5, 0.75, 1.0, 1.5, 2.0],
 [0.5, 0.75, 1.0, 1.5, 2.0],
 [0.5, 0.75, 1.0, 1.5, 2.0]]

In [49]:
v[0] = 'Pytho'
m

[[0.5, 0.75, 1.0, 1.5, 2.0],
 [0.5, 0.75, 1.0, 1.5, 2.0],
 [0.5, 0.75, 1.0, 1.5, 2.0]]

In [50]:
v

['Pytho', 0.75, 1.0, 1.5, 2.0]

In [51]:
v = [0.5, 0.75 , 1.0, 1.5, 2.0]


In [52]:
import array

In [53]:
a = array.array('f', v)
a

array('f', [0.5, 0.75, 1.0, 1.5, 2.0])

In [54]:
a.append(0.5)
a

array('f', [0.5, 0.75, 1.0, 1.5, 2.0, 0.5])

In [55]:
a.extend([5.0, 6.75])

In [56]:
a

array('f', [0.5, 0.75, 1.0, 1.5, 2.0, 0.5, 5.0, 6.75])

In [57]:
a*2

array('f', [0.5, 0.75, 1.0, 1.5, 2.0, 0.5, 5.0, 6.75, 0.5, 0.75, 1.0, 1.5, 2.0, 0.5, 5.0, 6.75])

In [58]:
# a.append('string')

In [59]:
a.tolist()

[0.5, 0.75, 1.0, 1.5, 2.0, 0.5, 5.0, 6.75]

In [60]:
f = open('array.apy', 'wb')
a.tofile(f)
f.close()

In [61]:
with open('array.apy','wb') as f:
    a.tofile(f)

In [62]:
!ls -n arr*

-rw-r--r--@ 1 501  20  32 Jan  4 11:16 array.apy


In [63]:
b = array.array('f')

In [64]:
with open('array.apy', 'rb') as f:
    b.fromfile(f, 5)

In [65]:
b

array('f', [0.5, 0.75, 1.0, 1.5, 2.0])

In [66]:
b = array.array('d')
# the dfference in type codes lead to "wrong" numbers
with  open ('array.apy', 'rb') as f:
    b.fromfile(f, 2)

In [67]:
b

array('d', [0.0004882813645963324, 0.12500002956949174])

In [68]:
import numpy as np

In [69]:
a = np.array([0, 0.5, 1.0 ,1.5, 2.0])
a

array([0. , 0.5, 1. , 1.5, 2. ])

In [70]:
type(a)

numpy.ndarray

In [71]:
a = np.array(['a', 'b', 'c'])
a

array(['a', 'b', 'c'], dtype='<U1')

In [72]:
a = np.arange(2,20,2)
a

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [73]:
a = np.arange(8, dtype=np.float64)
a

array([0., 1., 2., 3., 4., 5., 6., 7.])

In [74]:
a[5:]

array([5., 6., 7.])

In [75]:
a[:2]

array([0., 1.])

In [76]:
a.sum()

np.float64(28.0)

In [77]:
a.std()

np.float64(2.29128784747792)

In [78]:
a.cumsum()
# the cumulative sum of all elements (starting at index position 0)

array([ 0.,  1.,  3.,  6., 10., 15., 21., 28.])

In [79]:
l = [0., 0.5, 1.5, 3., 5.]
2*l
# scalar multiplication with list objects leads to a repetition of elements

[0.0, 0.5, 1.5, 3.0, 5.0, 0.0, 0.5, 1.5, 3.0, 5.0]

In [80]:
a

array([0., 1., 2., 3., 4., 5., 6., 7.])

In [81]:
2*a

array([ 0.,  2.,  4.,  6.,  8., 10., 12., 14.])

In [82]:
2**a

array([  1.,   2.,   4.,   8.,  16.,  32.,  64., 128.])

In [83]:
a**2

array([ 0.,  1.,  4.,  9., 16., 25., 36., 49.])

In [84]:
a**a

array([1.00000e+00, 1.00000e+00, 4.00000e+00, 2.70000e+01, 2.56000e+02,
       3.12500e+03, 4.66560e+04, 8.23543e+05])

In [85]:
type(a)

numpy.ndarray

In [86]:
type(l)

list

In [87]:
np.exp(a)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03])

In [88]:
np.sqrt(a)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131])

In [89]:
np.sqrt(2.5)

np.float64(1.5811388300841898)

In [90]:
import math
math.sqrt(2.5)

1.5811388300841898

In [91]:
#math.sqrt(a)

In [92]:
%timeit np.sqrt(2.5)

44.5 ns ± 1.28 ns per loop (mean ± std. dev. of 7 runs, 10,000,000 loops each)


In [93]:
%timeit math.sqrt(2.5)

12.9 ns ± 0.137 ns per loop (mean ± std. dev. of 7 runs, 100,000,000 loops each)


In [94]:
b = np.array([a, a*2])
b

array([[ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.],
       [ 0.,  2.,  4.,  6.,  8., 10., 12., 14.]])

In [95]:
b[0]

array([0., 1., 2., 3., 4., 5., 6., 7.])

In [96]:
b[0,2]

np.float64(2.0)

In [97]:
b[:,1]

array([1., 2.])

In [98]:
b.sum()

np.float64(84.0)

In [99]:
b.sum(axis=0)

array([ 0.,  3.,  6.,  9., 12., 15., 18., 21.])

In [100]:
b.sum(axis=1)

array([28., 56.])

In [101]:
c = np.zeros((2,3), dtype='i', order='C')
c

array([[0, 0, 0],
       [0, 0, 0]], dtype=int32)

In [102]:
c = np.ones((2,3,4), dtype='i', order='C')
c

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int32)

In [103]:
d = np.zeros_like(c, dtype='f8', order='C')
d

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [104]:
e = np.empty((2,3,2))
e

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

In [105]:
f= np.empty_like(c)
f

array([[[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]]], dtype=int32)

In [106]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [107]:
g = np.linspace(5,15,12)

In [108]:
g

array([ 5.        ,  5.90909091,  6.81818182,  7.72727273,  8.63636364,
        9.54545455, 10.45454545, 11.36363636, 12.27272727, 13.18181818,
       14.09090909, 15.        ])

In [109]:
g.size

12

In [ ]:
g.itemsize
# number of byte used to represent one element

8

In [111]:
g.ndim

1

In [ ]:
g.shape
# The shape of the ndarray object

(12,)

In [ ]:
g.dtype
# The type of the elements

dtype('float64')

In [114]:
g.nbytes

96

In [115]:
g = np.arange(15)

In [116]:
g

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [117]:
np.shape(g)

(15,)

In [118]:
g.reshape((3,5))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [120]:
h = g.reshape((5,3))
h

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [ ]:
h.T
# transpose of the new ndarray object

array([[ 0,  3,  6,  9, 12],
       [ 1,  4,  7, 10, 13],
       [ 2,  5,  8, 11, 14]])

In [122]:
h.transpose()

array([[ 0,  3,  6,  9, 12],
       [ 1,  4,  7, 10, 13],
       [ 2,  5,  8, 11, 14]])

In [123]:
g

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [124]:
np.resize(g,(3,1))

array([[0],
       [1],
       [2]])

In [125]:
np.resize(g,(1,5))

array([[0, 1, 2, 3, 4]])

In [126]:
np.resize(g,(2,5))

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [128]:
n = np.resize(g, (5,4))
n

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14,  0],
       [ 1,  2,  3,  4]])

In [129]:
h

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [ ]:
np.hstack((h, 2*h))
# horizontal stacking of two ndarray objects

array([[ 0,  1,  2,  0,  2,  4],
       [ 3,  4,  5,  6,  8, 10],
       [ 6,  7,  8, 12, 14, 16],
       [ 9, 10, 11, 18, 20, 22],
       [12, 13, 14, 24, 26, 28]])

In [ ]:
np.vstack((h, 0.5*h))
# vertical stacking of two ndarray objects

array([[ 0. ,  1. ,  2. ],
       [ 3. ,  4. ,  5. ],
       [ 6. ,  7. ,  8. ],
       [ 9. , 10. , 11. ],
       [12. , 13. , 14. ],
       [ 0. ,  0.5,  1. ],
       [ 1.5,  2. ,  2.5],
       [ 3. ,  3.5,  4. ],
       [ 4.5,  5. ,  5.5],
       [ 6. ,  6.5,  7. ]])

In [134]:
h

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [135]:
h.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [136]:
h.flatten(order='C')

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [137]:
h.flatten(order='F')

array([ 0,  3,  6,  9, 12,  1,  4,  7, 10, 13,  2,  5,  8, 11, 14])

In [138]:
for i in h.flat:
    print(i, end=',')

0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,

In [139]:
for i in h.ravel(order='C'):
    print(i, end=',')

0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,

In [140]:
for i in h.ravel(order='F'):
    print(i, end=',')

0,3,6,9,12,1,4,7,10,13,2,5,8,11,14,

In [141]:
h

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [142]:
h>8

array([[False, False, False],
       [False, False, False],
       [False, False, False],
       [ True,  True,  True],
       [ True,  True,  True]])

In [143]:
h<=7

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True, False],
       [False, False, False],
       [False, False, False]])

In [144]:
h ==5

array([[False, False, False],
       [False, False,  True],
       [False, False, False],
       [False, False, False],
       [False, False, False]])

In [145]:
(h==5).astype(int)

array([[0, 0, 0],
       [0, 0, 1],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [146]:
(h>4)&(h<=12)

array([[False, False, False],
       [False, False,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True, False, False]])

In [147]:
h[h>8]

array([ 9, 10, 11, 12, 13, 14])

In [148]:
h[(h>4)&(h<=12)]

array([ 5,  6,  7,  8,  9, 10, 11, 12])

In [ ]:
h[(h<4)|(h>=12)]
# give me all values greater than... or smaller than or equal to ...

array([ 0,  1,  2,  3, 12, 13, 14])

In [ ]:
np.where(h>7,1,0)
# in the new object, set 1 if True and 0 otherwise

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [151]:
np.where(h%2 ==0, 'even', 'odd')

array([['even', 'odd', 'even'],
       ['odd', 'even', 'odd'],
       ['even', 'odd', 'even'],
       ['odd', 'even', 'odd'],
       ['even', 'odd', 'even']], dtype='<U4')

In [ ]:
np.where(h <=7, h*2, h/2)
# in the new object, set two times the h element if True and half the h element otherwise

array([[ 0. ,  2. ,  4. ],
       [ 6. ,  8. , 10. ],
       [12. , 14. ,  4. ],
       [ 4.5,  5. ,  5.5],
       [ 6. ,  6.5,  7. ]])

In [153]:
import random
I= 5000

In [154]:
%time mat = [[random.gauss(0,1) for j in range(I)]\
             for i in range(I)]

CPU times: user 3.76 s, sys: 111 ms, total: 3.87 s
Wall time: 3.88 s


In [155]:
mat[0][:5]

[-0.7836136150742568,
 -1.2646064928229208,
 1.6865216197838584,
 -0.6903830777029328,
 0.9685476765306033]

In [ ]:
%time sum ([sum(l) for l in mat])
# the sums of the single list objects are first calculated during 
# a list comprehension; then the sum of the sums is taken

CPU times: user 63.1 ms, sys: 1.62 ms, total: 64.7 ms
Wall time: 64.3 ms


579.5833570262041

In [ ]:
import sys
sum([sys.getsizeof(l) for l in mat])
# This adds up thememory usage of all list objects


209400000