Chap 4. Numerical Computing with Numpy

In [1]:
v = [0.5, 0.75 , 1.0, 1.5, 2.0]

In [2]:
m = [v,v,v]
m

[[0.5, 0.75, 1.0, 1.5, 2.0],
 [0.5, 0.75, 1.0, 1.5, 2.0],
 [0.5, 0.75, 1.0, 1.5, 2.0]]

In [3]:
m[1]

[0.5, 0.75, 1.0, 1.5, 2.0]

In [4]:
m[1][0]

0.5

In [5]:
v1 = [0.2, 1.5]
v2 = [1, 2]
m=[v1, v2]
c= [m, m]
c

[[[0.2, 1.5], [1, 2]], [[0.2, 1.5], [1, 2]]]

In [6]:
c[1][1][0]

1

In [7]:
v = [0.5, 0.75 , 1.0, 1.5, 2.0]
m = [v, v, v]
m

[[0.5, 0.75, 1.0, 1.5, 2.0],
 [0.5, 0.75, 1.0, 1.5, 2.0],
 [0.5, 0.75, 1.0, 1.5, 2.0]]

In [8]:
v[0] = 'Python'
m

[['Python', 0.75, 1.0, 1.5, 2.0],
 ['Python', 0.75, 1.0, 1.5, 2.0],
 ['Python', 0.75, 1.0, 1.5, 2.0]]

In [9]:
from copy import deepcopy
v = [0.5, 0.75 , 1.0, 1.5, 2.0]
m = 3*[deepcopy(v),]
m

[[0.5, 0.75, 1.0, 1.5, 2.0],
 [0.5, 0.75, 1.0, 1.5, 2.0],
 [0.5, 0.75, 1.0, 1.5, 2.0]]

In [10]:
v[0] = 'Pytho'
m

[[0.5, 0.75, 1.0, 1.5, 2.0],
 [0.5, 0.75, 1.0, 1.5, 2.0],
 [0.5, 0.75, 1.0, 1.5, 2.0]]

In [11]:
v

['Pytho', 0.75, 1.0, 1.5, 2.0]

In [12]:
v = [0.5, 0.75 , 1.0, 1.5, 2.0]


In [13]:
import array

In [14]:
a = array.array('f', v)
a

array('f', [0.5, 0.75, 1.0, 1.5, 2.0])

In [15]:
a.append(0.5)
a

array('f', [0.5, 0.75, 1.0, 1.5, 2.0, 0.5])

In [16]:
a.extend([5.0, 6.75])

In [17]:
a

array('f', [0.5, 0.75, 1.0, 1.5, 2.0, 0.5, 5.0, 6.75])

In [18]:
a*2

array('f', [0.5, 0.75, 1.0, 1.5, 2.0, 0.5, 5.0, 6.75, 0.5, 0.75, 1.0, 1.5, 2.0, 0.5, 5.0, 6.75])

In [19]:
# a.append('string')

In [20]:
a.tolist()

[0.5, 0.75, 1.0, 1.5, 2.0, 0.5, 5.0, 6.75]

In [21]:
f = open('array.apy', 'wb')
a.tofile(f)
f.close()

In [22]:
with open('array.apy','wb') as f:
    a.tofile(f)

In [23]:
!ls -n arr*

-rw-rw-r-- 1 1000 1000 32 Jan  4 11:46 array.apy


In [24]:
b = array.array('f')

In [25]:
with open('array.apy', 'rb') as f:
    b.fromfile(f, 5)

In [26]:
b

array('f', [0.5, 0.75, 1.0, 1.5, 2.0])

In [27]:
b = array.array('d')
# the dfference in type codes lead to "wrong" numbers
with  open ('array.apy', 'rb') as f:
    b.fromfile(f, 2)

In [28]:
b

array('d', [0.0004882813645963324, 0.12500002956949174])

In [29]:
import numpy as np

In [30]:
a = np.array([0, 0.5, 1.0 ,1.5, 2.0])
a

array([0. , 0.5, 1. , 1.5, 2. ])

In [31]:
type(a)

numpy.ndarray

In [32]:
a = np.array(['a', 'b', 'c'])
a

array(['a', 'b', 'c'], dtype='<U1')

In [33]:
a = np.arange(2,20,2)
a

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [34]:
a = np.arange(8, dtype=np.float64)
a

array([0., 1., 2., 3., 4., 5., 6., 7.])

In [35]:
a[5:]

array([5., 6., 7.])

In [36]:
a[:2]

array([0., 1.])

In [37]:
a.sum()

np.float64(28.0)

In [38]:
a.std()

np.float64(2.29128784747792)

In [39]:
a.cumsum()
# the cumulative sum of all elements (starting at index position 0)

array([ 0.,  1.,  3.,  6., 10., 15., 21., 28.])

In [40]:
l = [0., 0.5, 1.5, 3., 5.]
2*l
# scalar multiplication with list objects leads to a repetition of elements

[0.0, 0.5, 1.5, 3.0, 5.0, 0.0, 0.5, 1.5, 3.0, 5.0]

In [41]:
a

array([0., 1., 2., 3., 4., 5., 6., 7.])

In [42]:
2*a

array([ 0.,  2.,  4.,  6.,  8., 10., 12., 14.])

In [43]:
2**a

array([  1.,   2.,   4.,   8.,  16.,  32.,  64., 128.])

In [44]:
a**2

array([ 0.,  1.,  4.,  9., 16., 25., 36., 49.])

In [45]:
a**a

array([1.00000e+00, 1.00000e+00, 4.00000e+00, 2.70000e+01, 2.56000e+02,
       3.12500e+03, 4.66560e+04, 8.23543e+05])

In [46]:
type(a)

numpy.ndarray

In [47]:
type(l)

list

In [48]:
np.exp(a)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03])

In [49]:
np.sqrt(a)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131])

In [50]:
np.sqrt(2.5)

np.float64(1.5811388300841898)

In [51]:
import math
math.sqrt(2.5)

1.5811388300841898

In [52]:
#math.sqrt(a)

In [53]:
%timeit np.sqrt(2.5)

750 ns ± 19 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [54]:
%timeit math.sqrt(2.5)

29.5 ns ± 1.16 ns per loop (mean ± std. dev. of 7 runs, 10,000,000 loops each)


In [55]:
b = np.array([a, a*2])
b

array([[ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.],
       [ 0.,  2.,  4.,  6.,  8., 10., 12., 14.]])

In [56]:
b[0]

array([0., 1., 2., 3., 4., 5., 6., 7.])

In [57]:
b[0,2]

np.float64(2.0)

In [58]:
b[:,1]

array([1., 2.])

In [59]:
b.sum()

np.float64(84.0)

In [60]:
b.sum(axis=0)

array([ 0.,  3.,  6.,  9., 12., 15., 18., 21.])

In [61]:
b.sum(axis=1)

array([28., 56.])

In [62]:
c = np.zeros((2,3), dtype='i', order='C')
c

array([[0, 0, 0],
       [0, 0, 0]], dtype=int32)

In [63]:
c = np.ones((2,3,4), dtype='i', order='C')
c

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int32)

In [64]:
d = np.zeros_like(c, dtype='f8', order='C')
d

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [65]:
e = np.empty((2,3,2))
e

array([[[3.76547473e-315, 0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000],
        [2.52908754e-081, 3.41985440e-032]],

       [[5.40382489e-038, 5.26254123e-037],
        [8.69542799e-043, 1.13039175e-042],
        [2.06072948e+184, 1.34657429e+165]]])

In [66]:
f= np.empty_like(c)
f

array([[[ 762140571,          0,          0,          0],
        [         0,          0,          0,          0],
        [         0,  791884078,  808477285,  962998837]],

       [[ 943154224,  942826341, 1667316020,  946233958],
        [ 962867509,  926114870, 1664168503,  926496101],
        [1647522915, 1714644529,  878850658, 1647796792]]], dtype=int32)

In [67]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [68]:
g = np.linspace(5,15,12)

In [69]:
g

array([ 5.        ,  5.90909091,  6.81818182,  7.72727273,  8.63636364,
        9.54545455, 10.45454545, 11.36363636, 12.27272727, 13.18181818,
       14.09090909, 15.        ])

In [70]:
g.size

12

In [71]:
g.itemsize
# number of byte used to represent one element

8

In [72]:
g.ndim

1

In [73]:
g.shape
# The shape of the ndarray object

(12,)

In [74]:
g.dtype
# The type of the elements

dtype('float64')

In [75]:
g.nbytes

96

In [76]:
g = np.arange(15)

In [77]:
g

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [78]:
np.shape(g)

(15,)

In [79]:
g.reshape((3,5))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [80]:
h = g.reshape((5,3))
h

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [81]:
h.T
# transpose of the new ndarray object

array([[ 0,  3,  6,  9, 12],
       [ 1,  4,  7, 10, 13],
       [ 2,  5,  8, 11, 14]])

In [82]:
h.transpose()

array([[ 0,  3,  6,  9, 12],
       [ 1,  4,  7, 10, 13],
       [ 2,  5,  8, 11, 14]])

In [83]:
g

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [84]:
np.resize(g,(3,1))

array([[0],
       [1],
       [2]])

In [85]:
np.resize(g,(1,5))

array([[0, 1, 2, 3, 4]])

In [86]:
np.resize(g,(2,5))

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [87]:
n = np.resize(g, (5,4))
n

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14,  0],
       [ 1,  2,  3,  4]])

In [88]:
h

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [89]:
np.hstack((h, 2*h))
# horizontal stacking of two ndarray objects

array([[ 0,  1,  2,  0,  2,  4],
       [ 3,  4,  5,  6,  8, 10],
       [ 6,  7,  8, 12, 14, 16],
       [ 9, 10, 11, 18, 20, 22],
       [12, 13, 14, 24, 26, 28]])

In [90]:
np.vstack((h, 0.5*h))
# vertical stacking of two ndarray objects

array([[ 0. ,  1. ,  2. ],
       [ 3. ,  4. ,  5. ],
       [ 6. ,  7. ,  8. ],
       [ 9. , 10. , 11. ],
       [12. , 13. , 14. ],
       [ 0. ,  0.5,  1. ],
       [ 1.5,  2. ,  2.5],
       [ 3. ,  3.5,  4. ],
       [ 4.5,  5. ,  5.5],
       [ 6. ,  6.5,  7. ]])

In [91]:
h

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [92]:
h.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [93]:
h.flatten(order='C')

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [94]:
h.flatten(order='F')

array([ 0,  3,  6,  9, 12,  1,  4,  7, 10, 13,  2,  5,  8, 11, 14])

In [95]:
for i in h.flat:
    print(i, end=',')

0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,

In [96]:
for i in h.ravel(order='C'):
    print(i, end=',')

0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,

In [97]:
for i in h.ravel(order='F'):
    print(i, end=',')

0,3,6,9,12,1,4,7,10,13,2,5,8,11,14,

In [98]:
h

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [99]:
h>8

array([[False, False, False],
       [False, False, False],
       [False, False, False],
       [ True,  True,  True],
       [ True,  True,  True]])

In [100]:
h<=7

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True, False],
       [False, False, False],
       [False, False, False]])

In [101]:
h ==5

array([[False, False, False],
       [False, False,  True],
       [False, False, False],
       [False, False, False],
       [False, False, False]])

In [102]:
(h==5).astype(int)

array([[0, 0, 0],
       [0, 0, 1],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [103]:
(h>4)&(h<=12)

array([[False, False, False],
       [False, False,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True, False, False]])

In [104]:
h[h>8]

array([ 9, 10, 11, 12, 13, 14])

In [105]:
h[(h>4)&(h<=12)]

array([ 5,  6,  7,  8,  9, 10, 11, 12])

In [106]:
h[(h<4)|(h>=12)]
# give me all values greater than... or smaller than or equal to ...

array([ 0,  1,  2,  3, 12, 13, 14])

In [107]:
np.where(h>7,1,0)
# in the new object, set 1 if True and 0 otherwise

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [108]:
np.where(h%2 ==0, 'even', 'odd')

array([['even', 'odd', 'even'],
       ['odd', 'even', 'odd'],
       ['even', 'odd', 'even'],
       ['odd', 'even', 'odd'],
       ['even', 'odd', 'even']], dtype='<U4')

In [109]:
np.where(h <=7, h*2, h/2)
# in the new object, set two times the h element if True and half the h element otherwise

array([[ 0. ,  2. ,  4. ],
       [ 6. ,  8. , 10. ],
       [12. , 14. ,  4. ],
       [ 4.5,  5. ,  5.5],
       [ 6. ,  6.5,  7. ]])

In [110]:
import random
I= 5000

In [111]:
%time mat = [[random.gauss(0,1) for j in range(I)]\
             for i in range(I)]

CPU times: user 10.3 s, sys: 368 ms, total: 10.6 s
Wall time: 10.6 s


In [112]:
mat[0][:5]

[0.8482171978108329,
 -0.9329397846002977,
 1.0890038623261769,
 1.1722162430291199,
 -1.082378723621175]

In [113]:
%time sum ([sum(l) for l in mat])
# the sums of the single list objects are first calculated during 
# a list comprehension; then the sum of the sums is taken

CPU times: user 261 ms, sys: 3 ms, total: 264 ms
Wall time: 263 ms


4355.976658295833

In [114]:
import sys
sum([sys.getsizeof(l) for l in mat])
# This adds up thememory usage of all list objects


209400000

In [115]:
%time mat = np.random.standard_normal((I,I))

CPU times: user 804 ms, sys: 98 ms, total: 902 ms
Wall time: 930 ms


In [116]:
%time mat.sum()

CPU times: user 22.1 ms, sys: 1 ms, total: 23.1 ms
Wall time: 21.3 ms


np.float64(872.5820871610335)

In [ ]:
mat.nbytes
# The numpy approach also saves some memory since the memory 
# overhaed of the ndarray object is tiny compared to the size of the data itself.

200000000

In [118]:
sys.getsizeof(mat)

200000128

In [119]:
dt = np.dtype([('Name', 'S10'), ('Age', 'i4'), ('Heigth', 'f'), ('Children/Pets', 'i4', 2)])

In [120]:
dt

dtype([('Name', 'S10'), ('Age', '<i4'), ('Heigth', '<f4'), ('Children/Pets', '<i4', (2,))])

In [124]:
dt = np.dtype({'names': ['Name', 'Age', 'Heigth', 'Children/Pets'], 'formats' : 'O int float int,int'.split()})

In [125]:
dt

dtype([('Name', 'O'), ('Age', '<i8'), ('Heigth', '<f8'), ('Children/Pets', [('f0', '<i8'), ('f1', '<i8')])])

In [126]:
s = np.array([('Smith', 45, 1.83, (0,1)),('Jones', 53, 1.72, (2,2))], dtype=dt)

In [127]:
s

array([('Smith', 45, 1.83, (0, 1)), ('Jones', 53, 1.72, (2, 2))],
      dtype=[('Name', 'O'), ('Age', '<i8'), ('Heigth', '<f8'), ('Children/Pets', [('f0', '<i8'), ('f1', '<i8')])])

In [128]:
type(s)

numpy.ndarray

In [129]:
s['Name']

array(['Smith', 'Jones'], dtype=object)

In [131]:
s['Heigth'].mean()

np.float64(1.775)

In [132]:
s[0]

np.void(('Smith', 45, 1.83, (0, 1)), dtype=[('Name', 'O'), ('Age', '<i8'), ('Heigth', '<f8'), ('Children/Pets', [('f0', '<i8'), ('f1', '<i8')])])

In [133]:
s[1]['Age']

np.int64(53)

In [134]:
np.random.seed(100)
r= np.arange(12).reshape((4,3))
s= np.arange(12).reshape((4,3))*0.5

In [135]:
r

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [136]:
s

array([[0. , 0.5, 1. ],
       [1.5, 2. , 2.5],
       [3. , 3.5, 4. ],
       [4.5, 5. , 5.5]])

In [137]:
r+s

array([[ 0. ,  1.5,  3. ],
       [ 4.5,  6. ,  7.5],
       [ 9. , 10.5, 12. ],
       [13.5, 15. , 16.5]])

In [138]:
r+3

array([[ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [139]:
2*r

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16],
       [18, 20, 22]])

In [140]:
2*r+3

array([[ 3,  5,  7],
       [ 9, 11, 13],
       [15, 17, 19],
       [21, 23, 25]])

In [141]:
r

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [142]:
r.shape

(4, 3)

In [143]:
s = np.arange(0,12,4)
s

array([0, 4, 8])

In [144]:
r+s

array([[ 0,  5, 10],
       [ 3,  8, 13],
       [ 6, 11, 16],
       [ 9, 14, 19]])

In [146]:
s= np.arange(0,12,3)
s

array([0, 3, 6, 9])

In [147]:
r+s

ValueError: operands could not be broadcast together with shapes (4,3) (4,) 

In [148]:
r.transpose()+s

array([[ 0,  6, 12, 18],
       [ 1,  7, 13, 19],
       [ 2,  8, 14, 20]])

In [152]:
sr = s.reshape(-1,1)
sr

array([[0],
       [3],
       [6],
       [9]])

In [150]:
sr.shape

(4, 1)

In [151]:
r+s.reshape(-1,1)

array([[ 0,  1,  2],
       [ 6,  7,  8],
       [12, 13, 14],
       [18, 19, 20]])