## Chapter 6. Object-Oriented Programming

In [2]:
class HumanBeing(object):
    def __init__(self, first_name, eye_color):
        self.first_name = first_name
        self.eye_color = eye_color
        self.position = 0
    def walk_steps(self, steps):
        self.position += steps

In [3]:
Sandra = HumanBeing('Sandra' , 'blue')

In [4]:
Sandra.first_name

'Sandra'

In [5]:
Sandra.position

0

In [6]:
Sandra.walk_steps(5)

In [7]:
Sandra.position

5

In [8]:
n = 5

In [9]:
type(n)

int

In [10]:
n.numerator

5

In [11]:
n.bit_length()

3

In [12]:
n+n

10

In [13]:
2*n

10

In [ ]:
n.__sizeof__()
#calling the special method __sizeof__() to get the memory usage in bytes.

28

In [15]:
l = [1,2,3,4]

In [16]:
type(l)

list

In [17]:
l[0]

1

In [18]:
l.append(10)

In [19]:
l+l

[1, 2, 3, 4, 10, 1, 2, 3, 4, 10]

In [20]:
2*l

[1, 2, 3, 4, 10, 1, 2, 3, 4, 10]

In [21]:
sum(l)

20

In [23]:
l.__sizeof__()

104

In [24]:
import numpy as np

In [27]:
a =np.arange(16).reshape((4,4))

In [28]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [29]:
type(a)

numpy.ndarray

In [30]:
a.nbytes

128

In [ ]:
a.sum()
#A method (aggregation).


np.int64(120)

In [38]:
a.cumsum(axis=0)
#A method (no aggregation).


array([[ 0,  1,  2,  3],
       [ 4,  6,  8, 10],
       [12, 15, 18, 21],
       [24, 28, 32, 36]])

In [33]:
a+a

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22],
       [24, 26, 28, 30]])

In [34]:
2*a

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22],
       [24, 26, 28, 30]])

In [35]:
sum(a)

array([24, 28, 32, 36])

In [36]:
np.sum(a)

np.int64(120)

In [ ]:
a.__sizeof__()
#Calling the special method __sizeof__() to get the memory usage in bytes.


128

In [39]:
import pandas as pd

In [41]:
df = pd.DataFrame(a, columns = list('abcd'))

In [42]:
type(df)

pandas.core.frame.DataFrame

In [44]:
df.columns

Index(['a', 'b', 'c', 'd'], dtype='object')

In [45]:
df.sum()

a    24
b    28
c    32
d    36
dtype: int64

In [47]:
df.cumsum()

a   b   c   d
0   0   1   2   3
1   4   6   8  10
2  12  15  18  21
3  24  28  32  36

In [49]:
df.cumsum(axis=1)

a   b   c   d
0   0   1   3   6
1   4   9  15  22
2   8  17  27  38
3  12  25  39  54

In [50]:
df+df

a   b   c   d
0   0   2   4   6
1   8  10  12  14
2  16  18  20  22
3  24  26  28  30

In [51]:
2*df

a   b   c   d
0   0   2   4   6
1   8  10  12  14
2  16  18  20  22
3  24  26  28  30

In [52]:
np.sum(df)

c:\Users\user\AppData\Local\Programs\Python\Python313\Lib\site-packages\numpy\_core\fromnumeric.py:84: FutureWarning: The behavior of DataFrame.sum with axis=None is deprecated, in a future version this will reduce over both axes and return a scalar. To retain the old behavior, pass axis=0 (or do not pass axis)
  return reduction(axis=axis, out=out, **passkwargs)


a    24
b    28
c    32
d    36
dtype: int64

In [53]:
df.__sizeof__()

260

In [54]:
class FinancialInstrument(object):
    pass

In [55]:
fi = FinancialInstrument()

In [56]:
type(fi)

__main__.FinancialInstrument

In [ ]:
# Every Python object comes with certain “special” attributes and methods (from object); here, the special method to retrieve the string representation is called.
fi

In [58]:
fi.__str__()

'<__main__.FinancialInstrument object at 0x0000012D6DAB3380>'

In [59]:
fi.price =100

In [60]:
fi.price

100

An important special method is __init__, which gets called during every instantia
tion of an object. It takes as parameters the object itself (self, by convention) and
potentially multiple others:

In [61]:
class FinancialInstrument(object):
    author = 'Yves Hilpisch'
    def __init__(self, symbol, price):
        self.symbol = symbol
        self.price = price


In [62]:
FinancialInstrument.author

'Yves Hilpisch'

In [63]:
aapl = FinancialInstrument('AAPL', 100)

In [65]:
aapl.symbol

'AAPL'

In [66]:
aapl.author

'Yves Hilpisch'

In [68]:
aapl.price=105

In [69]:
aapl.price

105

In [70]:
aapl

Prices of financial instruments change regularly, but the symbol of a financial instru
ment probably does not change. To introduce encapsulation to the class definition,
two methods, get_price() and set_price(), might be defined. The code that fol
lows additionally inherits from the previous class definition (and not from object
anymore):

In [71]:
class FinancialInstrument(FinancialInstrument):
    def get_price(self):
        return self.price
    def set_price(self, price):
        self.price=price

In [72]:
fi = FinancialInstrument('AAPL',100)

In [73]:
fi.get_price()

100

In [74]:
fi.set_price(105)

In [75]:
fi.get_price()

105

In [76]:
fi.price

105

In [77]:
class FinancialInstrument(object):
    def __init__(self, symbol, price):
        self.symbol = symbol
        self.__price = price  
    def get_price(self):
        return self.__price
    def set_price(self, price):
        self.__price = price

In [78]:
fi = FinancialInstrument('AAPL', 100)

In [79]:
fi.get_price()

100

In [80]:
fi.__price

AttributeError: 'FinancialInstrument' object has no attribute '__price'

In [81]:
fi._FinancialInstrument__price

100

In [82]:
fi._FinancialInstrument__price =105

In [83]:
fi.set_price(100)