## Chapter 6. Object-Oriented Programming

In [191]:
class HumanBeing(object):
    def __init__(self, first_name, eye_color):
        self.first_name = first_name
        self.eye_color = eye_color
        self.position = 0
    def walk_steps(self, steps):
        self.position += steps

In [192]:
Sandra = HumanBeing('Sandra' , 'blue')

In [193]:
Sandra.first_name

'Sandra'

In [194]:
Sandra.position

0

In [195]:
Sandra.walk_steps(5)

In [196]:
Sandra.position

5

In [197]:
n = 5

In [198]:
type(n)

int

In [199]:
n.numerator

5

In [200]:
n.bit_length()

3

In [201]:
n+n

10

In [202]:
2*n

10

In [203]:
n.__sizeof__()
#calling the special method __sizeof__() to get the memory usage in bytes.

28

In [204]:
l = [1,2,3,4]

In [205]:
type(l)

list

In [206]:
l[0]

1

In [207]:
l.append(10)

In [208]:
l+l

[1, 2, 3, 4, 10, 1, 2, 3, 4, 10]

In [209]:
2*l

[1, 2, 3, 4, 10, 1, 2, 3, 4, 10]

In [210]:
sum(l)

20

In [211]:
l.__sizeof__()

104

In [212]:
import numpy as np

In [213]:
a =np.arange(16).reshape((4,4))

In [214]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [215]:
type(a)

numpy.ndarray

In [216]:
a.nbytes

128

In [217]:
a.sum()
#A method (aggregation).


np.int64(120)

In [218]:
a.cumsum(axis=0)
#A method (no aggregation).


array([[ 0,  1,  2,  3],
       [ 4,  6,  8, 10],
       [12, 15, 18, 21],
       [24, 28, 32, 36]])

In [219]:
a+a

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22],
       [24, 26, 28, 30]])

In [220]:
2*a

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22],
       [24, 26, 28, 30]])

In [221]:
sum(a)

array([24, 28, 32, 36])

In [222]:
np.sum(a)

np.int64(120)

In [223]:
a.__sizeof__()
#Calling the special method __sizeof__() to get the memory usage in bytes.


128

In [224]:
import pandas as pd

In [225]:
df = pd.DataFrame(a, columns = list('abcd'))

In [226]:
type(df)

pandas.core.frame.DataFrame

In [227]:
df.columns

Index(['a', 'b', 'c', 'd'], dtype='object')

In [228]:
df.sum()

a    24
b    28
c    32
d    36
dtype: int64

In [229]:
df.cumsum()

a   b   c   d
0   0   1   2   3
1   4   6   8  10
2  12  15  18  21
3  24  28  32  36

In [230]:
df.cumsum(axis=1)

a   b   c   d
0   0   1   3   6
1   4   9  15  22
2   8  17  27  38
3  12  25  39  54

In [231]:
df+df

a   b   c   d
0   0   2   4   6
1   8  10  12  14
2  16  18  20  22
3  24  26  28  30

In [232]:
2*df

a   b   c   d
0   0   2   4   6
1   8  10  12  14
2  16  18  20  22
3  24  26  28  30

In [233]:
np.sum(df)

c:\Users\user\AppData\Local\Programs\Python\Python313\Lib\site-packages\numpy\_core\fromnumeric.py:84: FutureWarning: The behavior of DataFrame.sum with axis=None is deprecated, in a future version this will reduce over both axes and return a scalar. To retain the old behavior, pass axis=0 (or do not pass axis)
  return reduction(axis=axis, out=out, **passkwargs)


a    24
b    28
c    32
d    36
dtype: int64

In [234]:
df.__sizeof__()

260

In [235]:
class FinancialInstrument(object):
    pass

In [236]:
fi = FinancialInstrument()

In [237]:
type(fi)

__main__.FinancialInstrument

In [238]:
# Every Python object comes with certain “special” attributes and methods (from object); here, the special method to retrieve the string representation is called.
fi

In [239]:
fi.__str__()

'<__main__.FinancialInstrument object at 0x000001C6C1549BE0>'

In [240]:
fi.price =100

In [241]:
fi.price

100

An important special method is __init__, which gets called during every instantia
tion of an object. It takes as parameters the object itself (self, by convention) and
potentially multiple others:

In [242]:
class FinancialInstrument(object):
    author = 'Yves Hilpisch'
    def __init__(self, symbol, price):
        self.symbol = symbol
        self.price = price


In [243]:
FinancialInstrument.author

'Yves Hilpisch'

In [244]:
aapl = FinancialInstrument('AAPL', 100)

In [245]:
aapl.symbol

'AAPL'

In [246]:
aapl.author

'Yves Hilpisch'

In [247]:
aapl.price=105

In [248]:
aapl.price

105

In [249]:
aapl

Prices of financial instruments change regularly, but the symbol of a financial instru
ment probably does not change. To introduce encapsulation to the class definition,
two methods, get_price() and set_price(), might be defined. The code that fol
lows additionally inherits from the previous class definition (and not from object
anymore):

In [250]:
class FinancialInstrument(FinancialInstrument):
    def get_price(self):
        return self.price
    def set_price(self, price):
        self.price=price

In [251]:
fi = FinancialInstrument('AAPL',100)

In [252]:
fi.get_price()

100

In [253]:
fi.set_price(105)

In [254]:
fi.get_price()

105

In [255]:
fi.price

105

In [256]:
class FinancialInstrument(object):
    def __init__(self, symbol, price):
        self.symbol = symbol
        self.__price = price  
    def get_price(self):
        return self.__price
    def set_price(self, price):
        self.__price = price

In [257]:
fi = FinancialInstrument('AAPL', 100)

In [258]:
fi.get_price()

100

In [259]:
# fi.__price
# Trying to access the attribute directly raises an error.


In [260]:
fi._FinancialInstrument__price

100

In [261]:
fi._FinancialInstrument__price =105

In [262]:
fi.set_price(100)

In [263]:
class PortfolioPosition(object):
    def __init__(self, financial_instrument, position_size):
        self.position = financial_instrument
        self.__position_size = position_size
    def get_position_size(self):
        return self.__position_size
    def update_position_size(self, position_size):
        self.__position_size = position_size
    def get_position_value(self):
        return self.__position_size * \
        self.position.get_price()

In [264]:
pp = PortfolioPosition(fi, 10)
pp

In [265]:
pp.get_position_size()

10

In [266]:
pp.get_position_value()

1000

In [267]:
pp.position.get_price()

100

In [268]:
pp.position.set_price(105)

In [269]:
pp.get_position_value()

1050

In [270]:
class Vector(object):
    def __init__(self, x=0, y=0, z=0):
        self.x=x
        self.y=y
        self.z=z

In [271]:
v = Vector(1,2,3)

In [272]:
v

In [273]:
class Vector(Vector):
    def __repr__(self):
        return 'Vector(%r, %r, %r)' %(self.x, self.y, self.z)

In [274]:
v = Vector(1,2,3)

In [275]:
v

Vector(1, 2, 3)

In [276]:
print(v)

Vector(1, 2, 3)


In [277]:
class Vector(Vector):
    def __abs__(self):
        return (self.x**2 + self.y**2 + self.z**2)**0.5
    def __bool__(self):
        return bool(abs(self))

In [278]:
v = Vector( 1,2,-1)

In [279]:
abs(v)

2.449489742783178

In [280]:
bool(v)

True

In [281]:
v = Vector()

In [282]:
v

Vector(0, 0, 0)

In [283]:
abs(v)

0.0

In [284]:
bool(v)

False

In [285]:
class Vector(Vector):
    def __add__(self, other):
        x = self.x + other.x
        y = self.y + other.y
        z = self.z + other.z
        return Vector(x, y, z)
    def __mul__(self, scalar):
        return Vector(self.x*scalar,
                      self.y*scalar,
                      self.z*scalar)

In [286]:
v = Vector(1,2,3)

In [287]:
v + Vector(2,3,4)

Vector(3, 5, 7)

In [288]:
v*2

Vector(2, 4, 6)

In [289]:
class Vector(Vector):
    def __len__(self):
        return 3
    def __getitem__(self,i):
        if i in [0, -3]: return self.x
        elif i in [1, -2]: return self.y
        elif i in [2, -1]: return self.z
        else: raise IndexError('Index out of range.')

In [290]:
v = Vector(1,2,3)

In [291]:
len(v)

3

In [292]:
v[0]

1

In [293]:
v[-2]

2

In [294]:
v[3]

IndexError: Index out of range.

In [295]:
class Vector(Vector):
    def __iter__(self):
        for i in range(len(self)):
            yield self[i]

In [296]:
v = Vector(1,2,3)

In [ ]:
for i in range(3):
    print(v[i])
    #Indirect iteration using index values (via __getitem__).


1
2
3


In [ ]:
for coordinate in v:
    print(coordinate)
    #Direct iteration over the class instance (using __iter__).


1
2
3
